class TradingError(Exception): pass 
class WalletError(TradingError): pass   
class DEXError(TradingError): pass 
class NetworkError(TradingError): pass 
class ConnectionError(NetworkError): pass 
class InsufficientFundsError(TradingError): pass 
class InvalidAddressError(WalletError): pass 
class TransactionError(TradingError): pass 
class SecurityError(WalletError): pass 
class RiskLimitExceededError(TradingError): pass 
class StrategyError(TradingError): pass 
class PortfolioError(TradingError): pass 
class OrderExecutionError(TradingError): pass 
class InvalidOrderError(TradingError): pass 
class SlippageExceededError(TradingError): pass 
class InsufficientLiquidityError(DEXError): pass 
